// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgPyvMT2EzAj6qZc2W_rOSGd07U_ay2qY',
    appId: '1:409073451750:web:dfc7ae264174be0b7c3127',
    messagingSenderId: '409073451750',
    projectId: 'point-f33cb',
    authDomain: 'point-f33cb.firebaseapp.com',
    storageBucket: 'point-f33cb.firebasestorage.app',
    measurementId: 'G-DL9V3S0FHM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAh7eHmFzw-LSPQwU6vL0-ryEgTu3TT9sU',
    appId: '1:409073451750:android:f2d29d9519d63b7f7c3127',
    messagingSenderId: '409073451750',
    projectId: 'point-f33cb',
    storageBucket: 'point-f33cb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDI-AWGdIucLLT0z35Y238XniyK8G8KlIY',
    appId: '1:409073451750:ios:cfd66c52f68e3d677c3127',
    messagingSenderId: '409073451750',
    projectId: 'point-f33cb',
    storageBucket: 'point-f33cb.firebasestorage.app',
    iosBundleId: 'com.point.agency',
  );
}
