// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBrhKKoBcqWyO2ssSuupBK11T_Ym7-kek',
    appId: '1:801208232022:web:561af1516e8de3e2df73f7',
    messagingSenderId: '801208232022',
    projectId: 'point-agency-production',
    authDomain: 'point-agency-production.firebaseapp.com',
    storageBucket: 'point-agency-production.firebasestorage.app',
    measurementId: 'G-BKBGBWXDSG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzRtPj4CjJc8Ssdq4wMuOzYaeVNlY-bD0',
    appId: '1:801208232022:android:2e2f793727332909df73f7',
    messagingSenderId: '801208232022',
    projectId: 'point-agency-production',
    storageBucket: 'point-agency-production.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBswDVWhLwK3yutlxl9dksZ6nG2kfulIfw',
    appId: '1:801208232022:ios:dd57a4964f9e0794df73f7',
    messagingSenderId: '801208232022',
    projectId: 'point-agency-production',
    storageBucket: 'point-agency-production.firebasestorage.app',
    iosBundleId: 'com.point.agency',
  );

}